AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Different options for implementing rest services with AWS API Gateway and Lambda functions. 

Globals:
  Function:
    Timeout: 20


Resources:


    EchoLiApi:
      Type: AWS::Serverless::Api
      Properties:
        Name: echo-li-validate
        StageName: Prod
        TracingEnabled: True
        DefinitionBody:
          swagger: "2.0"
          info:
            title: "EchoAPI"
          x-amazon-apigateway-request-validators:
            Validate Body: 
              validateRequestBody: True
              validateRequestParameters: False
          paths:
            /echo:
              post:
                consumes:
                - "application/json"
                produces:
                - "application/json"
                x-amazon-apigateway-request-validator: "Validate Body"
                parameters:
                - in: "body"
                  name: "Inventor"
                  required: true
                  schema: 
                    $ref: "#/definitions/Inventor"
                responses:
                  "200": 
                    description: "200 response"
                x-amazon-apigateway-integration:
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EchoLiFunc.Arn}/invocations
                  responses:
                    default:
                      statusCode: 200
                  passthroughBehavior: when_no_match
                  httpMethod: POST
                  type: AWS
                x-amazon-apigateway-any-method:
                  produces: application/json
          definitions: 
            Inventor:
              description: "Inventor model"
              type: "object"
              required:
                - "name"
                - "wiki"
              properties:
                name:
                  type: "string"
                wiki:
                  type: "string"
                knownFor:
                  type: "string"
              

    EchoLiFunc:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: EchoFunctionJS
        Handler: app.lambdaHandlerStraight
        Runtime: nodejs10.x
        Events:
          Request:
            Type: Api
            Properties:
              RestApiId: !Ref EchoLiApi
              Path: /echo
              Method: post



